### ISSUE TITLE
Unable to loop mount bdemount-ed volume

### ISSUE THREAD

**Issue by michelbehr** [libyal/libbde#43] opened 2019-07-13 16:34 UTC
In the Mounting manual it says that all you have to do after using bdemount to mount is to do a "loop mount". But it doesn't work on MacOS, the system requires the specification of the type with -t option, and when I do specify, it says "Block device required". What do I do now?

(BTW: Shouldn't those details be described in the Mounting manual page? Is anyone being able to do this loop mount without specifying type? I'm confused...)

**Comment by michelbehr** [comment] 2019-07-13 16:41
By the way: loop option doesn't work, see below.

```
michels-MacBook-Air-4:libbde-20190701 michelbehr$ sudo mount -t ntfs -o loop,ro /Volumes/Pendrive/bde1 /Volumes/NTFS/
mount_ntfs: -o loop: option not supported
```

**Comment by joachimmetz** [comment] 2019-07-13 18:41
> Shouldn't those details be described in the Mounting manual page?

What specifically should be described? How to loop mount on the operating system of your choice? That is infeasible.

Since you're running on macOS you likely need to run something similar to?
`hdiutil attach -imagekey diskimage-class=CRawDiskImage /Volumes/Pendrive/bde1`

**Comment by joachimmetz** [comment] 2019-07-13 18:43
marking as invalid since issue seems to be related to on how to use loop mount functionality of macOS

**Closed** 2019-07-13 19:03 UTC
Labels: invalid, question

**Comment by michelbehr** [comment] 2019-07-13 19:11
IMHO the documentation is part of the system. The command you mentioned (which works - thanks!) should be included in the Mounting manual. Yes, I'm using MacOS, and there are OS specific instructions in the manual, this would be an additional one (i.e., if you are running Linux, use this "loop" command, if you are using MacOS, hdiutil command is the way to go).

**Comment by joachimmetz** [comment] 2019-07-13 19:21
> IMHO the documentation is part of the system. 

Yes, and MacOS has documented its usage of hdiutil. IMHO this is basic knowledge of your system, not something this project needs to reproduce.

Also, too many operating systems with too many variations, which makes it infeasible and too time consuming to maintain.
