### ISSUE TITLE
How to decrypt the VMK by using BitLocker Recovery Key?

### ISSUE THREAD

**Issue by MaxFuwin** [libyal/libbde#65] opened 2023-04-20 00:30 UTC
Hello Joachim, I have read the documentation but the problem is I was using a lib called AES from Cryptodome in Python decrypting the VMK which means when I keyed in “iv = 0”in python and it said that the length of initial vector must be 7-12 bytes, so I wasn’t sure about the length because if I keyed in the wrong length of initial vector and I will get the wrong VMK and I had the Recovery Key and the VMK which is encrypted by the BitLocker Recovery Key. But I didn't know how to use the BitLocker Recovery Key to decrypt the whole VMK

**Comment by joachimmetz** [comment] 2023-04-20 03:02
I don't have sufficient details to help you case. What is known is documented and in the code.

**Comment by joachimmetz** [comment] 2023-04-20 03:03
Marking as duplicate of https://github.com/libyal/libbde/issues/64

**Comment by MaxFuwin** [comment] 2023-04-20 03:59
Do you know how to decrypt the VMK by using BitLocker Recovery Key in libbde ?

**Comment by joachimmetz** [comment] 2023-04-20 04:04
> Do you know how to decrypt the VMK by using BitLocker Recovery Key in libbde ?

I don't understand this question? libbde can decrypt an encrypted volume

First of all there is no single VMK, the VMK is dependent on the data, how the VMK is protected is dependent on the key protectors used.

If you cannot be specific in your questions in about your specific situation, I cannot help you.

**Closed** 2023-04-20 04:34 UTC
Labels: duplicate, question
